kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pod-checkpointer-operator
  namespace: openshift-pod-checkpointer
rules:
- apiGroups:
  - pod.checkpointer.operator.openshift.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
