// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCheckpointerOperator) DeepCopyInto(out *PodCheckpointerOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCheckpointerOperator.
func (in *PodCheckpointerOperator) DeepCopy() *PodCheckpointerOperator {
	if in == nil {
		return nil
	}
	out := new(PodCheckpointerOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodCheckpointerOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCheckpointerOperatorList) DeepCopyInto(out *PodCheckpointerOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodCheckpointerOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCheckpointerOperatorList.
func (in *PodCheckpointerOperatorList) DeepCopy() *PodCheckpointerOperatorList {
	if in == nil {
		return nil
	}
	out := new(PodCheckpointerOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodCheckpointerOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCheckpointerOperatorSpec) DeepCopyInto(out *PodCheckpointerOperatorSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCheckpointerOperatorSpec.
func (in *PodCheckpointerOperatorSpec) DeepCopy() *PodCheckpointerOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(PodCheckpointerOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCheckpointerOperatorStatus) DeepCopyInto(out *PodCheckpointerOperatorStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCheckpointerOperatorStatus.
func (in *PodCheckpointerOperatorStatus) DeepCopy() *PodCheckpointerOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(PodCheckpointerOperatorStatus)
	in.DeepCopyInto(out)
	return out
}
