// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCheckpointer) DeepCopyInto(out *PodCheckpointer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCheckpointer.
func (in *PodCheckpointer) DeepCopy() *PodCheckpointer {
	if in == nil {
		return nil
	}
	out := new(PodCheckpointer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodCheckpointer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCheckpointerList) DeepCopyInto(out *PodCheckpointerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodCheckpointer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCheckpointerList.
func (in *PodCheckpointerList) DeepCopy() *PodCheckpointerList {
	if in == nil {
		return nil
	}
	out := new(PodCheckpointerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodCheckpointerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCheckpointerSpec) DeepCopyInto(out *PodCheckpointerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCheckpointerSpec.
func (in *PodCheckpointerSpec) DeepCopy() *PodCheckpointerSpec {
	if in == nil {
		return nil
	}
	out := new(PodCheckpointerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCheckpointerStatus) DeepCopyInto(out *PodCheckpointerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCheckpointerStatus.
func (in *PodCheckpointerStatus) DeepCopy() *PodCheckpointerStatus {
	if in == nil {
		return nil
	}
	out := new(PodCheckpointerStatus)
	in.DeepCopyInto(out)
	return out
}
